### ISSUE TITLE
Thanks for your contribution, I`ve fork and update 5.2

### ISSUE THREAD

**Issue by yangchao0033** [roeybiran/dash-swift#1]
Swift 5.2 Docsets : [https://github.com/yangchao0033/dash-swift](https://github.com/yangchao0033/dash-swift)

**Comment by roeybiran** [comment]
Merged. Did you use the included generator script? If so, did it work well for you?

Thanks!

**Comment by yangchao0033** [comment]
@roeybiran Yes, it work very well 👍
